os:
  - linux
  - osx
language: perl6
perl6:
  - latest
install:
  - rakudobrew build-zef
  - zef install --depsonly --/test --/build .
script:
  - zef build $PWD
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/
sudo: false
