os:
  - linux
  - osx
language: perl6
perl6:
  - latest
install:
  - rakudobrew build-zef
  - zef install --depsonly --/test --/build .
script:
  - perl6 -MZef::Build -e 'Zef::Build.new.build(~$*CWD)'
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/
sudo: false
